"""new cols added in user table

Revision ID: 09ad034c3f9f
Revises: 5a836f7a564d
Create Date: 2025-05-18 03:34:36.978251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09ad034c3f9f'
down_revision: Union[str, None] = '5a836f7a564d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_codes', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('opt_expires', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('opt_expires')
        batch_op.drop_column('otp_codes')

    # ### end Alembic commands ###
