"""on delete option added in affirmations schema

Revision ID: 3447a3340b46
Revises: 61dbe4d8f819
Create Date: 2025-05-14 01:06:31.982677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3447a3340b46'
down_revision: Union[str, None] = '61dbe4d8f819'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('affirmations', schema=None) as batch_op:
        batch_op.drop_constraint('affirmations_journal_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'journals', ['journal_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('affirmations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('affirmations_journal_id_fkey', 'journals', ['journal_id'], ['id'])

    # ### end Alembic commands ###
