"""input summary col added in affirmations table

Revision ID: 4faed74f8598
Revises: 0d91efb9bf4b
Create Date: 2025-05-09 02:28:11.554241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4faed74f8598'
down_revision: Union[str, None] = '0d91efb9bf4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('affirmations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('input_summary', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('affirmations', schema=None) as batch_op:
        batch_op.drop_column('input_summary')

    # ### end Alembic commands ###
