"""session id removed

Revision ID: 5a836f7a564d
Revises: 3447a3340b46
Create Date: 2025-05-16 05:40:21.683448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a836f7a564d'
down_revision: Union[str, None] = '3447a3340b46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_constraint('refresh_tokens_session_id_key', type_='unique')
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('refresh_tokens_session_id_key', ['session_id'])

    # ### end Alembic commands ###
