"""made cols null in token table

Revision ID: c3a60da4349d
Revises: 09ad034c3f9f
Create Date: 2025-05-21 02:18:40.465507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3a60da4349d'
down_revision: Union[str, None] = '09ad034c3f9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('refresh_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.alter_column('expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
        batch_op.alter_column('refresh_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###
