"""affirmation col datatype changed to JSON in affirmations table

Revision ID: cd6602d11faa
Revises: 4faed74f8598
Create Date: 2025-05-09 02:55:00.957997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd6602d11faa'
down_revision: Union[str, None] = '4faed74f8598'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Explicitly cast affirmations column to JSON
    op.execute("""
        ALTER TABLE affirmations
        ALTER COLUMN affirmations
        TYPE JSON
        USING affirmations::json
    """)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('affirmations', schema=None) as batch_op:
        batch_op.alter_column('affirmations',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
