"""New tables journals and affirmations added

Revision ID: ed49da5a15b9
Revises: 849e6292c303
Create Date: 2025-05-02 15:57:22.104983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed49da5a15b9'
down_revision: Union[str, None] = '849e6292c303'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('sentiment_label', sa.String(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journals_id'), ['id'], unique=False)

    op.create_table('affirmations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('affirmations', sa.String(), nullable=False),
    sa.Column('journal_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('affirmations')
    with op.batch_alter_table('journals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journals_id'))

    op.drop_table('journals')
    # ### end Alembic commands ###
